#language: java
#jdk:
 # - oraclejdk8
  #- oraclejdk7

  language: "java"
  maven-version: "3.2"
#before_deploy:
#  -"mvn clean install -U -DskipTests=true"
# Show the jwt token, as we aint afraid of no leakage
#before_install:
#  - export | grep SAUCE_

#env:
#  global:
#    - SAUCE_USERNAME=nievesPrueba
#addons:
  #sauce_connect: true
  #  username: "nievesPrueba2"
   # access_key: "2301a36e-36fa-4500-82f6-18ea4e62f601"
    #username: "Your Sauce Labs access key"
    #access_key: "Your Sauce Labs access key"
