language: java
jdk:
  - oraclejdk8

before_deploy:
    on:
      tags: true

#script: if [[ "${TRAVIS_TAG}" =~ (.*)-TESTME ]]; then mvn test; fi
script: if [[ "${TRAVIS_TAG}" =~ (.*)-TESTME ]]; then mvn test; git checkout -b "${TRAVIS_TAG}"; git push origin "${TRAVIS_TAG}"; fi

#after_success:
#  - echo "${TRAVIS_TAG}"
#  - if [[ "${TRAVIS_TAG}" =~ (.*)-TESTME ]]; then mvn test; fi

addons:
  #sauce_connect: true
    username: "travis-arq-testing"
    access_key: "dfcd0c77-25c6-42ba-92f3-d85e08bb036c"
    #username: "Your Sauce Labs access key"
    #access_key: "Your Sauce Labs access key"
