language: java
jdk:
  - oraclejdk8

#before_deploy:
#  -"mvn clean install -U -DskipTests=true"
# Show the jwt token, as we aint afraid of no leakage
#before_install:
#  - export | grep SAUCE_

#env:
# -TRAVIS_TAG="mi_tag"

before_deploy:
    on:
      tags: true


after_success:
  - echo "${TRAVIS_TAG}"
  - if [[ "${TRAVIS_TAG}" =~ (.*)-TESTME ]]; then
      mvn test;
  fi


addons:
  #sauce_connect: true
    username: "travis-arq-testing"
    access_key: "dfcd0c77-25c6-42ba-92f3-d85e08bb036c"
    #username: "Your Sauce Labs access key"
    #access_key: "Your Sauce Labs access key"
